font_family JetBrainsMono NF
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

background_opacity 1.0
dynamic_background_opacity no
confirm_os_window_close 0
cursor_trail 3
cursor_trail_decay 0.08 0.35
cursor_trail_start_threshold 1
cursor_trail_color #f5f5f5
linux_display_server auto

scrollback_lines 4000
wheel_scroll_min_lines 1
enable_audio_bell no
window_padding_width 6

tab_bar_style separator
tab_separator "  "
active_tab_font_style bold
inactive_tab_font_style normal

include current-theme.conf
